house_data <- read.table("household_power_consumption.txt", header = TRUE, sep = ";", na.strings = "?")
subset_data <- house_data[house_data$Date %in% c("1/2/2007","2/2/2007") ,]
date_time <- strptime(paste(subset_data$Date, subset_data$Time, sep=" "), "%d/%m/%Y %H:%M:%S")
sub_metering_1 <- as.numeric(subset_data$Sub_metering_1)
sub_metering_2 <- as.numeric(subset_data$Sub_metering_2)
sub_metering_3 <- as.numeric(subset_data$Sub_metering_3)
png(file="plot3.png", width=480, height=480)
plot(date_time, sub_metering_1, type="l", ylab="Energy sub_metering_", xlab="")
lines(date_time, sub_metering_2, type="l", col="red")
lines(date_time, sub_metering_3, type="l", col="blue")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty=1, lwd=3, col=c("black", "red", "blue"))
dev.off()