house_data <- read.table("household_power_consumption.txt", header = TRUE, sep = ";", na.strings = "?")
subset_data <- house_data[house_data$Date %in% c("1/2/2007","2/2/2007") ,]
subset_data$Timestamp <-paste(subset_data$Date,subset_data$Time)
date_time <- strptime(paste(subset_data$Date, subset_data$Time, sep=" "), "%d/%m/%Y %H:%M:%S")
sub_metering_1 <- as.numeric(subset_data$Sub_metering_1)
sub_metering_2 <- as.numeric(subset_data$Sub_metering_2)
sub_metering_3 <- as.numeric(subset_data$Sub_metering_3)
global_active_power <- as.numeric(subset_data$Global_active_power)
global_reactive_power <- as.numeric(subset_data$Global_reactive_power)
voltage <- as.numeric(subset_data$Voltage)
png(file="plot4.png", width=480, height=480)
par(mfcol = c(2,2))
plot(date_time,global_active_power,type="l",xlab="",ylab="Global Active Power")
plot(date_time, sub_metering_1, type="l", ylab="Energy sub metering", xlab="")
lines(date_time, sub_metering_2, type="l", col="red")
lines(date_time, sub_metering_3, type="l", col="blue")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty=1, lwd=3, col=c("black", "red", "blue"))
plot(date_time, voltage, type="l", xlab="date_time", ylab="Voltage")
plot(date_time, global_reactive_power, type="l", xlab="date_time", ylab="Global_reactive_power")
dev.off()